# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/devjeetroy/Development/CUDA Matrix Library V2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/devjeetroy/Development/CUDA Matrix Library V2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/devjeetroy/Development/CUDA Matrix Library V2/CMakeFiles" "/home/devjeetroy/Development/CUDA Matrix Library V2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/devjeetroy/Development/CUDA Matrix Library V2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CUDA_Matrix_Library_V2

# Build rule for target.
CUDA_Matrix_Library_V2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CUDA_Matrix_Library_V2
.PHONY : CUDA_Matrix_Library_V2

# fast build rule for target.
CUDA_Matrix_Library_V2/fast:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/build
.PHONY : CUDA_Matrix_Library_V2/fast

#=============================================================================
# Target rules for targets named CUDA_Matrix_Library_V2_LIB

# Build rule for target.
CUDA_Matrix_Library_V2_LIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CUDA_Matrix_Library_V2_LIB
.PHONY : CUDA_Matrix_Library_V2_LIB

# fast build rule for target.
CUDA_Matrix_Library_V2_LIB/fast:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2_LIB.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2_LIB.dir/build
.PHONY : CUDA_Matrix_Library_V2_LIB/fast

cpuMatrix.o: cpuMatrix.cpp.o
.PHONY : cpuMatrix.o

# target to build an object file
cpuMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/cpuMatrix.cpp.o
.PHONY : cpuMatrix.cpp.o

cpuMatrix.i: cpuMatrix.cpp.i
.PHONY : cpuMatrix.i

# target to preprocess a source file
cpuMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/cpuMatrix.cpp.i
.PHONY : cpuMatrix.cpp.i

cpuMatrix.s: cpuMatrix.cpp.s
.PHONY : cpuMatrix.s

# target to generate assembly for a file
cpuMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/cpuMatrix.cpp.s
.PHONY : cpuMatrix.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/main.cpp.s
.PHONY : main.cpp.s

mnist_loader.o: mnist_loader.cpp.o
.PHONY : mnist_loader.o

# target to build an object file
mnist_loader.cpp.o:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/mnist_loader.cpp.o
.PHONY : mnist_loader.cpp.o

mnist_loader.i: mnist_loader.cpp.i
.PHONY : mnist_loader.i

# target to preprocess a source file
mnist_loader.cpp.i:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/mnist_loader.cpp.i
.PHONY : mnist_loader.cpp.i

mnist_loader.s: mnist_loader.cpp.s
.PHONY : mnist_loader.s

# target to generate assembly for a file
mnist_loader.cpp.s:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/mnist_loader.cpp.s
.PHONY : mnist_loader.cpp.s

utilities.o: utilities.cpp.o
.PHONY : utilities.o

# target to build an object file
utilities.cpp.o:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/utilities.cpp.o
.PHONY : utilities.cpp.o

utilities.i: utilities.cpp.i
.PHONY : utilities.i

# target to preprocess a source file
utilities.cpp.i:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/utilities.cpp.i
.PHONY : utilities.cpp.i

utilities.s: utilities.cpp.s
.PHONY : utilities.s

# target to generate assembly for a file
utilities.cpp.s:
	$(MAKE) -f CMakeFiles/CUDA_Matrix_Library_V2.dir/build.make CMakeFiles/CUDA_Matrix_Library_V2.dir/utilities.cpp.s
.PHONY : utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CUDA_Matrix_Library_V2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CUDA_Matrix_Library_V2_LIB"
	@echo "... cpuMatrix.o"
	@echo "... cpuMatrix.i"
	@echo "... cpuMatrix.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mnist_loader.o"
	@echo "... mnist_loader.i"
	@echo "... mnist_loader.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

